import {deleteFalseValues} from './deleteFalseValues.js';
import {fillArray} from './fillArray.js';
import {findStrInStr} from './findStrInStr.js';
import {getFactorial} from './getFactorial.js';
import {getMaxNumbersArray} from './getMaxNumbersArray.js';
import {getMaxWordLengthOfString} from './getMaxWordLengthOfString.js';
import {getOneArrayOfSeveral} from './getOneArrayOfSeveral.js';
import {getPartOfString} from './getPartOfString.js';
import {setWordsCase} from './setWordsCase.js';
import {splitArray} from './splitArray.js';

// console.log(deleteFalseValues([ "",0,null,undefined,60,-0,"20"]));
// console.log(fillArray([], -10));
// console.log(findStrInStr(["aBcsadsa", "abb"]));
// console.log(getFactorial(4));
// console.log(getMaxNumbersArray([[1, 2, 3], [4, 5], [6, 7, 8, 9]]));
// console.log(getMaxWordLengthOfString("hi world"));
// console.log(getOneArrayOfSeveral([1, 2, 3], [4, 5], 1));
// console.log(getPartOfString("wasdwasdwasd", 4));
// console.log(setWordsCase("GOOD MORNING XFX"));
console.log(splitArray([1,2,3,4,5,6,7,8,9,10,11], 3));